# Generated by Django 5.2 on 2025-04-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='marital_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('id_doc', models.CharField(max_length=13)),
                ('issuing_authority', models.CharField(max_length=20)),
                ('issuing_date', models.DateField()),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('cep_address', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('number_address', models.CharField(max_length=10)),
                ('main_phone', models.CharField(max_length=13)),
                ('other_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('reg_date', models.DateField()),
                ('del_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('registration_user', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities_name', to='core.cities')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marital_status', to='core.marital_status')),
                ('status_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_person', to='core.status')),
            ],
        ),
    ]
