# Generated by Django 5.2 on 2025-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='del_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='mod_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
