# Generated by Django 5.2 on 2025-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_beneficiary_del_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='registration_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
